# Generated by Django 6.0.3 on 2026-03-31 23:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sobres', '0002_cargar_sobre_publico'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='sobres',
            name='nombre',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AddIndex(
            model_name='sobres',
            index=models.Index(fields=['-fecha_creacion'], name='sobres_sobr_fecha_c_a632d5_idx'),
        ),
        migrations.AddIndex(
            model_name='sobres',
            index=models.Index(fields=['usuario', 'activo'], name='sobres_sobr_usuario_cedb6d_idx'),
        ),
    ]
