# Generated by Django 6.0.3 on 2026-03-31 23:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='perfil',
            options={'verbose_name': 'Perfil', 'verbose_name_plural': 'Perfiles'},
        ),
        migrations.AddIndex(
            model_name='perfil',
            index=models.Index(fields=['fecha_nacimiento'], name='usuarios_pe_fecha_n_d92b95_idx'),
        ),
    ]
