# Generated by Django 6.0.3 on 2026-04-01 05:52

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sobres', '0003_alter_sobres_nombre_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prestamo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto_total', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('monto_pagado', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('completado', models.BooleanField(default=False)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('sobre_destino', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prestamo_recibidos', to='sobres.sobres')),
                ('sobre_origen', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prestamo_dados', to='sobres.sobres')),
            ],
            options={
                'verbose_name': 'Prestamo',
                'verbose_name_plural': 'Prestamos',
                'indexes': [models.Index(fields=['sobre_origen', 'completado'], name='prestamo_pr_sobre_o_a4e3d9_idx'), models.Index(fields=['sobre_destino', 'completado'], name='prestamo_pr_sobre_d_b24c3c_idx')],
            },
        ),
    ]
