# Generated by Django 5.1.6 on 2025-05-08 00:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='sobres',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=300)),
                ('saldo', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('limite', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
    ]
