# Generated by Django 6.0.3 on 2026-04-01 05:52

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sobres', '0003_alter_sobres_nombre_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(max_length=2, verbose_name=[('DE', 'deposito'), ('RE', 'retiro'), ('PR', 'prestamo')])),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('descripcion', models.CharField(blank=True, max_length=255)),
                ('saldo_anterior', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('saldo_nuevo', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('sobre', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transaccion_sobre', to='sobres.sobres')),
            ],
            options={
                'verbose_name': 'Transaccion',
                'verbose_name_plural': 'Transacciones',
                'indexes': [models.Index(fields=['sobre', '-fecha_creacion'], name='transaccion_sobre_i_106476_idx')],
            },
        ),
    ]
